### ISSUE TITLE
Building issue

### ISSUE THREAD

**Issue by nspsck** [liangyingy/lcd_binding_micropython#4]
Hi, I followed the commands on [the documents](https://lcd-binding-micropython.readthedocs.io/en/latest/) and run into these issues trying to build the firmware using the official micropython repo.

The messages are as follow: (mainly caused by some missing files)
Could you help me with that please?

```shell
/home/paul/esp/mpy/micropython/extmod/lcd_binding_micropython/lcd/hal/esp32/esp32.c:10:10: fatal error: esp_lcd_panel_io.h: No such file or directory
 #include "esp_lcd_panel_io.h"
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /home/paul/esp/esp-idf/components/tinyusb/tinyusb/src/osal/osal_freertos.h:33,
                 from /home/paul/esp/esp-idf/components/tinyusb/tinyusb/src/osal/osal.h:53,
                 from /home/paul/esp/esp-idf/components/tinyusb/tinyusb/src/tusb.h:38,
                 from /home/paul/esp/esp-idf/components/tinyusb/additions/include/tinyusb.h:18,
                 from /home/paul/esp/mpy/micropython/ports/esp32/usb.c:33:
/home/paul/esp/mpy/micropython/lib/berkeley-db-1.xx/PORT/include/queue.h:85: warning: "LIST_INIT" redefined
 #define LIST_INIT(head) {      \

In file included from /home/paul/esp/esp-idf/components/esp_rom/include/esp32s2/rom/lldesc.h:20,
                 from /home/paul/esp/esp-idf/components/soc/include/soc/lldesc.h:22,
                 from /home/paul/esp/esp-idf/components/driver/include/driver/spi_common.h:13,
                 from /home/paul/esp/esp-idf/components/driver/include/driver/spi_master.h:12,
                 from /home/paul/esp/mpy/micropython/ports/esp32/mphalport.h:38,
                 from /home/paul/esp/mpy/micropython/py/mphal.h:35,
                 from /home/paul/esp/mpy/micropython/ports/esp32/usb.c:28:
/home/paul/.espressif/tools/xtensa-esp32s2-elf/esp-2021r2-patch5-8.4.0/xtensa-esp32s2-elf/xtensa-esp32s2-elf/sys-include/sys/queue.h:563: note: this is the location of the previous definition
 #define LIST_INIT(head) do {      \

In file included from /home/paul/esp/esp-idf/components/tinyusb/tinyusb/src/osal/osal_freertos.h:33,
                 from /home/paul/esp/esp-idf/components/tinyusb/tinyusb/src/osal/osal.h:53,
                 from /home/paul/esp/esp-idf/components/tinyusb/tinyusb/src/tusb.h:38,
                 from /home/paul/esp/esp-idf/components/tinyusb/additions/include/tinyusb.h:18,
                 from /home/paul/esp/mpy/micropython/ports/esp32/usb.c:33:
/home/paul/esp/mpy/micropython/lib/berkeley-db-1.xx/PORT/include/queue.h:89: warning: "LIST_INSERT_AFTER" redefined
 #define LIST_INSERT_AFTER(listelm, elm, field) {   \

In file included from /home/paul/esp/esp-idf/components/esp_rom/include/esp32s2/rom/lldesc.h:20,
                 from /home/paul/esp/esp-idf/components/soc/include/soc/lldesc.h:22,
                 from /home/paul/esp/esp-idf/components/driver/include/driver/spi_common.h:13,
                 from /home/paul/esp/esp-idf/components/driver/include/driver/spi_master.h:12,
                 from /home/paul/esp/mpy/micropython/ports/esp32/mphalport.h:38,
                 from /home/paul/esp/mpy/micropython/py/mphal.h:35,
                 from /home/paul/esp/mpy/micropython/ports/esp32/usb.c:28:
/home/paul/.espressif/tools/xtensa-esp32s2-elf/esp-2021r2-patch5-8.4.0/xtensa-esp32s2-elf/xtensa-esp32s2-elf/sys-include/sys/queue.h:567: note: this is the location of the previous definition
 #define LIST_INSERT_AFTER(listelm, elm, field) do {   \

In file included from /home/paul/esp/esp-idf/components/tinyusb/tinyusb/src/osal/osal_freertos.h:33,
                 from /home/paul/esp/esp-idf/components/tinyusb/tinyusb/src/osal/osal.h:53,
                 from /home/paul/esp/esp-idf/components/tinyusb/tinyusb/src/tusb.h:38,
                 from /home/paul/esp/esp-idf/components/tinyusb/additions/include/tinyusb.h:18,
                 from /home/paul/esp/mpy/micropython/ports/esp32/usb.c:33:
/home/paul/esp/mpy/micropython/lib/berkeley-db-1.xx/PORT/include/queue.h:97: warning: "LIST_INSERT_HEAD" redefined
 #define LIST_INSERT_HEAD(head, elm, field) {    \

In file included from /home/paul/esp/esp-idf/components/esp_rom/include/esp32s2/rom/lldesc.h:20,
                 from /home/paul/esp/esp-idf/components/soc/include/soc/lldesc.h:22,
                 from /home/paul/esp/esp-idf/components/driver/include/driver/spi_common.h:13,
                 from /home/paul/esp/esp-idf/components/driver/include/driver/spi_master.h:12,
                 from /home/paul/esp/mpy/micropython/ports/esp32/mphalport.h:38,
                 from /home/paul/esp/mpy/micropython/py/mphal.h:35,
                 from /home/paul/esp/mpy/micropython/ports/esp32/usb.c:28:
/home/paul/.espressif/tools/xtensa-esp32s2-elf/esp-2021r2-patch5-8.4.0/xtensa-esp32s2-elf/xtensa-esp32s2-elf/sys-include/sys/queue.h:584: note: this is the location of the previous definition
 #define LIST_INSERT_HEAD(head, elm, field) do {    \

In file included from /home/paul/esp/esp-idf/components/tinyusb/tinyusb/src/osal/osal_freertos.h:33,
                 from /home/paul/esp/esp-idf/components/tinyusb/tinyusb/src/osal/osal.h:53,
                 from /home/paul/esp/esp-idf/components/tinyusb/tinyusb/src/tusb.h:38,
                 from /home/paul/esp/esp-idf/components/tinyusb/additions/include/tinyusb.h:18,
                 from /home/paul/esp/mpy/micropython/ports/esp32/usb.c:33:
/home/paul/esp/mpy/micropython/lib/berkeley-db-1.xx/PORT/include/queue.h:104: warning: "LIST_REMOVE" redefined
 #define LIST_REMOVE(elm, field) {     \

In file included from /home/paul/esp/esp-idf/components/esp_rom/include/esp32s2/rom/lldesc.h:20,
                 from /home/paul/esp/esp-idf/components/soc/include/soc/lldesc.h:22,
                 from /home/paul/esp/esp-idf/components/driver/include/driver/spi_common.h:13,
                 from /home/paul/esp/esp-idf/components/driver/include/driver/spi_master.h:12,
                 from /home/paul/esp/mpy/micropython/ports/esp32/mphalport.h:38,
                 from /home/paul/esp/mpy/micropython/py/mphal.h:35,
                 from /home/paul/esp/mpy/micropython/ports/esp32/usb.c:28:
/home/paul/.espressif/tools/xtensa-esp32s2-elf/esp-2021r2-patch5-8.4.0/xtensa-esp32s2-elf/xtensa-esp32s2-elf/sys-include/sys/queue.h:599: note: this is the location of the previous definition
 #define LIST_REMOVE(elm, field) do {     \

In file included from /home/paul/esp/esp-idf/components/tinyusb/tinyusb/src/osal/osal_freertos.h:33,
                 from /home/paul/esp/esp-idf/components/tinyusb/tinyusb/src/osal/osal.h:53,
                 from /home/paul/esp/esp-idf/components/tinyusb/tinyusb/src/tusb.h:38,
                 from /home/paul/esp/esp-idf/components/tinyusb/additions/include/tinyusb.h:18,
                 from /home/paul/esp/mpy/micropython/ports/esp32/usb.c:33:
/home/paul/esp/mpy/micropython/lib/berkeley-db-1.xx/PORT/include/queue.h:114: warning: "TAILQ_HEAD" redefined
 #define TAILQ_HEAD(name, type)      \

In file included from /home/paul/esp/esp-idf/components/esp_rom/include/esp32s2/rom/lldesc.h:20,
                 from /home/paul/esp/esp-idf/components/soc/include/soc/lldesc.h:22,
                 from /home/paul/esp/esp-idf/components/driver/include/driver/spi_common.h:13,
                 from /home/paul/esp/esp-idf/components/driver/include/driver/spi_master.h:12,
                 from /home/paul/esp/mpy/micropython/ports/esp32/mphalport.h:38,
                 from /home/paul/esp/mpy/micropython/py/mphal.h:35,
                 from /home/paul/esp/mpy/micropython/ports/esp32/usb.c:28:
/home/paul/.espressif/tools/xtensa-esp32s2-elf/esp-2021r2-patch5-8.4.0/xtensa-esp32s2-elf/xtensa-esp32s2-elf/sys-include/sys/queue.h:625: note: this is the location of the previous definition
 #define TAILQ_HEAD(name, type)      \

In file included from /home/paul/esp/esp-idf/components/tinyusb/tinyusb/src/osal/osal_freertos.h:33,
                 from /home/paul/esp/esp-idf/components/tinyusb/tinyusb/src/osal/osal.h:53,
                 from /home/paul/esp/esp-idf/components/tinyusb/tinyusb/src/tusb.h:38,
                 from /home/paul/esp/esp-idf/components/tinyusb/additions/include/tinyusb.h:18,
                 from /home/paul/esp/mpy/micropython/ports/esp32/usb.c:33:
/home/paul/esp/mpy/micropython/lib/berkeley-db-1.xx/PORT/include/queue.h:120: warning: "TAILQ_ENTRY" redefined
 #define TAILQ_ENTRY(type)      \

In file included from /home/paul/esp/esp-idf/components/esp_rom/include/esp32s2/rom/lldesc.h:20,
                 from /home/paul/esp/esp-idf/components/soc/include/soc/lldesc.h:22,
                 from /home/paul/esp/esp-idf/components/driver/include/driver/spi_common.h:13,
                 from /home/paul/esp/esp-idf/components/driver/include/driver/spi_master.h:12,
                 from /home/paul/esp/mpy/micropython/ports/esp32/mphalport.h:38,
                 from /home/paul/esp/mpy/micropython/py/mphal.h:35,
                 from /home/paul/esp/mpy/micropython/ports/esp32/usb.c:28:
/home/paul/.espressif/tools/xtensa-esp32s2-elf/esp-2021r2-patch5-8.4.0/xtensa-esp32s2-elf/xtensa-esp32s2-elf/sys-include/sys/queue.h:642: note: this is the location of the previous definition
 #define TAILQ_ENTRY(type)      \

In file included from /home/paul/esp/esp-idf/components/tinyusb/tinyusb/src/osal/osal_freertos.h:33,
                 from /home/paul/esp/esp-idf/components/tinyusb/tinyusb/src/osal/osal.h:53,
                 from /home/paul/esp/esp-idf/components/tinyusb/tinyusb/src/tusb.h:38,
                 from /home/paul/esp/esp-idf/components/tinyusb/additions/include/tinyusb.h:18,
                 from /home/paul/esp/mpy/micropython/ports/esp32/usb.c:33:
/home/paul/esp/mpy/micropython/lib/berkeley-db-1.xx/PORT/include/queue.h:129: warning: "TAILQ_INIT" redefined
 #define TAILQ_INIT(head) {      \

In file included from /home/paul/esp/esp-idf/components/esp_rom/include/esp32s2/rom/lldesc.h:20,
                 from /home/paul/esp/esp-idf/components/soc/include/soc/lldesc.h:22,
                 from /home/paul/esp/esp-idf/components/driver/include/driver/spi_common.h:13,
                 from /home/paul/esp/esp-idf/components/driver/include/driver/spi_master.h:12,
                 from /home/paul/esp/mpy/micropython/ports/esp32/mphalport.h:38,
                 from /home/paul/esp/mpy/micropython/py/mphal.h:35,
                 from /home/paul/esp/mpy/micropython/ports/esp32/usb.c:28:
/home/paul/.espressif/tools/xtensa-esp32s2-elf/esp-2021r2-patch5-8.4.0/xtensa-esp32s2-elf/xtensa-esp32s2-elf/sys-include/sys/queue.h:767: note: this is the location of the previous definition
 #define TAILQ_INIT(head) do {      \

In file included from /home/paul/esp/esp-idf/components/tinyusb/tinyusb/src/osal/osal_freertos.h:33,
                 from /home/paul/esp/esp-idf/components/tinyusb/tinyusb/src/osal/osal.h:53,
                 from /home/paul/esp/esp-idf/components/tinyusb/tinyusb/src/tusb.h:38,
                 from /home/paul/esp/esp-idf/components/tinyusb/additions/include/tinyusb.h:18,
                 from /home/paul/esp/mpy/micropython/ports/esp32/usb.c:33:
/home/paul/esp/mpy/micropython/lib/berkeley-db-1.xx/PORT/include/queue.h:134: warning: "TAILQ_INSERT_HEAD" redefined
 #define TAILQ_INSERT_HEAD(head, elm, field) {    \

In file included from /home/paul/esp/esp-idf/components/esp_rom/include/esp32s2/rom/lldesc.h:20,
                 from /home/paul/esp/esp-idf/components/soc/include/soc/lldesc.h:22,
                 from /home/paul/esp/esp-idf/components/driver/include/driver/spi_common.h:13,
                 from /home/paul/esp/esp-idf/components/driver/include/driver/spi_master.h:12,
                 from /home/paul/esp/mpy/micropython/ports/esp32/mphalport.h:38,
                 from /home/paul/esp/mpy/micropython/py/mphal.h:35,
                 from /home/paul/esp/mpy/micropython/ports/esp32/usb.c:28:
/home/paul/.espressif/tools/xtensa-esp32s2-elf/esp-2021r2-patch5-8.4.0/xtensa-esp32s2-elf/xtensa-esp32s2-elf/sys-include/sys/queue.h:798: note: this is the location of the previous definition
 #define TAILQ_INSERT_HEAD(head, elm, field) do {   \

In file included from /home/paul/esp/esp-idf/components/tinyusb/tinyusb/src/osal/osal_freertos.h:33,
                 from /home/paul/esp/esp-idf/components/tinyusb/tinyusb/src/osal/osal.h:53,
                 from /home/paul/esp/esp-idf/components/tinyusb/tinyusb/src/tusb.h:38,
                 from /home/paul/esp/esp-idf/components/tinyusb/additions/include/tinyusb.h:18,
                 from /home/paul/esp/mpy/micropython/ports/esp32/usb.c:33:
/home/paul/esp/mpy/micropython/lib/berkeley-db-1.xx/PORT/include/queue.h:144: warning: "TAILQ_INSERT_TAIL" redefined
 #define TAILQ_INSERT_TAIL(head, elm, field) {    \

In file included from /home/paul/esp/esp-idf/components/esp_rom/include/esp32s2/rom/lldesc.h:20,
                 from /home/paul/esp/esp-idf/components/soc/include/soc/lldesc.h:22,
                 from /home/paul/esp/esp-idf/components/driver/include/driver/spi_common.h:13,
                 from /home/paul/esp/esp-idf/components/driver/include/driver/spi_master.h:12,
                 from /home/paul/esp/mpy/micropython/ports/esp32/mphalport.h:38,
                 from /home/paul/esp/mpy/micropython/py/mphal.h:35,
                 from /home/paul/esp/mpy/micropython/ports/esp32/usb.c:28:
/home/paul/.espressif/tools/xtensa-esp32s2-elf/esp-2021r2-patch5-8.4.0/xtensa-esp32s2-elf/xtensa-esp32s2-elf/sys-include/sys/queue.h:811: note: this is the location of the previous definition
 #define TAILQ_INSERT_TAIL(head, elm, field) do {   \

In file included from /home/paul/esp/esp-idf/components/tinyusb/tinyusb/src/osal/osal_freertos.h:33,
                 from /home/paul/esp/esp-idf/components/tinyusb/tinyusb/src/osal/osal.h:53,
                 from /home/paul/esp/esp-idf/components/tinyusb/tinyusb/src/tusb.h:38,
                 from /home/paul/esp/esp-idf/components/tinyusb/additions/include/tinyusb.h:18,
                 from /home/paul/esp/mpy/micropython/ports/esp32/usb.c:33:
/home/paul/esp/mpy/micropython/lib/berkeley-db-1.xx/PORT/include/queue.h:151: warning: "TAILQ_INSERT_AFTER" redefined
 #define TAILQ_INSERT_AFTER(head, listelm, elm, field) {   \

In file included from /home/paul/esp/esp-idf/components/esp_rom/include/esp32s2/rom/lldesc.h:20,
                 from /home/paul/esp/esp-idf/components/soc/include/soc/lldesc.h:22,
                 from /home/paul/esp/esp-idf/components/driver/include/driver/spi_common.h:13,
                 from /home/paul/esp/esp-idf/components/driver/include/driver/spi_master.h:12,
                 from /home/paul/esp/mpy/micropython/ports/esp32/mphalport.h:38,
                 from /home/paul/esp/mpy/micropython/py/mphal.h:35,
                 from /home/paul/esp/mpy/micropython/ports/esp32/usb.c:28:
/home/paul/.espressif/tools/xtensa-esp32s2-elf/esp-2021r2-patch5-8.4.0/xtensa-esp32s2-elf/xtensa-esp32s2-elf/sys-include/sys/queue.h:773: note: this is the location of the previous definition
 #define TAILQ_INSERT_AFTER(head, listelm, elm, field) do {  \

In file included from /home/paul/esp/esp-idf/components/tinyusb/tinyusb/src/osal/osal_freertos.h:33,
                 from /home/paul/esp/esp-idf/components/tinyusb/tinyusb/src/osal/osal.h:53,
                 from /home/paul/esp/esp-idf/components/tinyusb/tinyusb/src/tusb.h:38,
                 from /home/paul/esp/esp-idf/components/tinyusb/additions/include/tinyusb.h:18,
                 from /home/paul/esp/mpy/micropython/ports/esp32/usb.c:33:
/home/paul/esp/mpy/micropython/lib/berkeley-db-1.xx/PORT/include/queue.h:161: warning: "TAILQ_REMOVE" redefined
 #define TAILQ_REMOVE(head, elm, field) {    \

In file included from /home/paul/esp/esp-idf/components/esp_rom/include/esp32s2/rom/lldesc.h:20,
                 from /home/paul/esp/esp-idf/components/soc/include/soc/lldesc.h:22,
                 from /home/paul/esp/esp-idf/components/driver/include/driver/spi_common.h:13,
                 from /home/paul/esp/esp-idf/components/driver/include/driver/spi_master.h:12,
                 from /home/paul/esp/mpy/micropython/ports/esp32/mphalport.h:38,
                 from /home/paul/esp/mpy/micropython/py/mphal.h:35,
                 from /home/paul/esp/mpy/micropython/ports/esp32/usb.c:28:
/home/paul/.espressif/tools/xtensa-esp32s2-elf/esp-2021r2-patch5-8.4.0/xtensa-esp32s2-elf/xtensa-esp32s2-elf/sys-include/sys/queue.h:839: note: this is the location of the previous definition
 #define TAILQ_REMOVE(head, elm, field) do {    \

Traceback (most recent call last):
  File "/home/paul/esp/mpy/micropython/py/makeqstrdefs.py", line 209, in <module>
    preprocess()
  File "/home/paul/esp/mpy/micropython/py/makeqstrdefs.py", line 76, in preprocess
    for output in p.imap(pp(flags), chunks):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 873, in next
    raise value
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/paul/esp/mpy/micropython/py/makeqstrdefs.py", line 60, in run
    return subprocess.check_output(args.pp + flags + files)
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
```

**Comment by lbuque** [comment]
@nspsck The following modification is also required, which I left out.

```diff
diff --git a/ports/esp32/main/CMakeLists.txt b/ports/esp32/main/CMakeLists.txt
index f8acfa905..209547892 100644
--- a/ports/esp32/main/CMakeLists.txt
+++ b/ports/esp32/main/CMakeLists.txt
@@ -124,6 +124,7 @@ set(IDF_COMPONENTS
     ulp
     vfs
     xtensa
+    esp_lcd
 )
 
 if(IDF_VERSION_MINOR GREATER_EQUAL 1 OR IDF_VERSION_MAJOR GREATER_EQUAL 5)
```

**Comment by nspsck** [comment]
That worked! Thanks!
